---
version: '3.9'
services:
  postgres_keycloak:
      image: postgres:latest
      restart: always
      networks:
        - keycloak
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      restart: always
      networks:
        - keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres_keycloak
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      ports:
        - 8443:8443
      depends_on:
        - postgres_keycloak
volumes:
  postgres_data:
networks:
  keycloak:
    driver: bridge
